#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

import sys
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter, Namespace
from os.path import abspath
from pathlib import Path

sys.path.append(str(Path(sys.argv[0]).resolve().parent.parent))

from common.common import check_workspace, run_command


def main() -> None:
    arguments = _get_arguments()

    workspace_dir = abspath(arguments.workspace_dir)

    check_workspace(workspace_dir)

    command = [arguments.python_bin, 'setup.py', 'bdist_wheel']

    output_dir = f'{workspace_dir}/dist'

    if arguments.output_dir:
        output_dir = abspath(arguments.output_dir)
        command.extend(['--dist-dir', output_dir])

    results = run_command(workspace_dir, command, r".*'(.+\.whl)'")

    for result in results:
        if not result.startswith('/'):
            result = f'{output_dir}/{result}' if arguments.output_dir else f'{workspace_dir}/{result}'
        print(result)


def _get_arguments() -> Namespace:
    parser = ArgumentParser(formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument('-p', '--python-bin', help='python executable to use', default='python3')
    parser.add_argument('-o', '--output-dir', help='package output directory')
    parser.add_argument('workspace_dir', help='workspace directory where setup.py is located')
    return parser.parse_args()


if __name__ == '__main__':
    main()
