#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

import sys
from os.path import dirname, abspath

sys.path.insert(0, dirname(abspath(__file__)))

from pack_python import main

if __name__ == "__main__":
    main()
