#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

import glob
import re
import shutil

import sys
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter, Namespace
from fileinput import FileInput
from os.path import abspath, dirname
from typing import Generator

sys.path.insert(0, dirname(abspath(__file__)))

from pack_common import check_workspace, run_command, get_absolute_path


def main() -> None:
    arguments = _get_arguments()

    workspace_dir = abspath(arguments.workspace_dir)

    check_workspace(workspace_dir)

    output_dir = f"{workspace_dir}/dist"

    results = _create_sources(arguments, workspace_dir, output_dir)

    build_dir = f"{output_dir}/{next(results)}".replace(".dev", "~dev")

    with open(f"{build_dir}/debian/rules", "w") as file:
        file.write(f"""#!/usr/bin/make -f

%:
\tdh $@ --with systemd

override_dh_auto_clean:
\tpython3 setup.py clean -a
\trm -rf build dist *.egg-info

override_dh_auto_build:
\tpython3 setup.py bdist_wheel

override_dh_auto_install:
\tmkdir -p debian/test-project/opt/dist
\tcp dist/*.whl debian/test-project/opt/dist/

""")

    results = _build_package(arguments, workspace_dir, build_dir)

    for result in results:
        print(f"{output_dir}/{result}")


def _create_sources(
        arguments: Namespace, workspace_dir: str, output_dir: str
) -> Generator[str, None, None]:
    package_name = _extract_package_name(workspace_dir)

    command_arguments = [
        "--package3",
        package_name,
        "--dist-dir",
        output_dir,
        "--compat",
        "10",
    ]

    if arguments.arguments:
        command_arguments.extend(arguments.arguments.split())

    if arguments.service_file:
        command_arguments.append("--with-dh-systemd")

    command = [
        arguments.python_bin,
        "setup.py",
        "--command-packages=stdeb.command",
        "sdist_dsc",
        *command_arguments,
    ]

    return run_command(workspace_dir, command, r"copying setup.py -> (.+)")


def _extract_package_name(workspace_dir: str) -> str:
    with open(f"{workspace_dir}/setup.py", "r") as file:
        setup_code = file.read()

    pattern = r'name\s*=\s*[\'"]([^\'"]+)[\'"]'

    match = re.search(pattern, setup_code)

    if match:
        return match.group(1)
    else:
        return workspace_dir.split("/")[-1]


def _build_package(arguments: Namespace, workspace_dir: str, build_dir: str) -> Generator[str, None, None]:
    debian_dir = f"{build_dir}/debian"

    _override_architecture(arguments.architecture, debian_dir)

    if service := arguments.service_file:
        service_file = get_absolute_path(service, workspace_dir)
        shutil.copy(service_file, debian_dir)

    if not arguments.extra_files:
        arguments.extra_files = []
    if pre_install := arguments.preinst_file:
        arguments.extra_files.append(pre_install)
    if post_install := arguments.postinst_file:
        arguments.extra_files.append(post_install)
    if pre_remove := arguments.prerm_file:
        arguments.extra_files.append(pre_remove)
    if post_remove := arguments.postrm_file:
        arguments.extra_files.append(post_remove)

    if arguments.extra_files:
        for item in arguments.extra_files:
            path = get_absolute_path(item, workspace_dir)
            for file in glob.glob(path):
                shutil.copy(file, debian_dir)

    command = ["dpkg-buildpackage", "-rfakeroot", "-us", "-uc", "-ui", "-b"]

    return run_command(build_dir, command, r".*'\.\./(.+\.deb)'")


def _override_architecture(architecture: str, debian_dir: str) -> None:
    with FileInput(f"{debian_dir}/control", inplace=True) as file:
        for line in file:
            if 'Architecture:' in line:
                line = f'Architecture: {architecture}\n'
            print(line, end='')


def _get_arguments() -> Namespace:
    parser = ArgumentParser(formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument("-a", "--arguments", help="extra arguments passed to stdeb")
    parser.add_argument("-p", "--python-bin", help="python executable to use", default="python3")
    parser.add_argument("-o", "--output-dir", help="package output directory")
    parser.add_argument("-s", "--service-file", help="service unit file path")
    parser.add_argument("--preinst-file", help="preinst file path")
    parser.add_argument("--postinst-file", help="postinst file path")
    parser.add_argument("--prerm-file", help="prerm file path")
    parser.add_argument("--postrm-file", help="postrm file path")
    parser.add_argument("-e", "--extra-files", help="add extra files into the debian folder before build",
                        action="append")
    parser.add_argument("-A", "--architecture", help="control file architecture", default="any")
    parser.add_argument("workspace_dir", help="workspace directory where setup.py is located")
    return parser.parse_known_args()[0]


if __name__ == "__main__":
    main()
