#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

import os
import sys
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter, Namespace
from os.path import abspath, dirname

sys.path.insert(0, dirname(abspath(__file__)))

from pack_common import check_workspace, run_command, get_absolute_path


def main() -> None:
    arguments = _get_arguments()

    workspace_dir = abspath(arguments.workspace_dir)

    check_workspace(workspace_dir)

    fpm_arguments = [
        "-s",
        "python",
        "-t",
        "deb",
        "--python-package-name-prefix",
        "python3",
        "--log",
        "error",
        "-f",
    ]

    if arguments.python_bin:
        fpm_arguments.extend(["--python-bin", arguments.python_bin])

    if arguments.arguments:
        fpm_arguments.extend(arguments.arguments.split())

    output_dir = f"{workspace_dir}/dist"

    if arguments.output_dir:
        output_dir = abspath(arguments.output_dir)

    os.makedirs(output_dir, exist_ok=True)
    fpm_arguments.extend(["--package", output_dir])

    if services := arguments.service_file:
        fpm_arguments.extend(["--deb-systemd-enable", "--deb-systemd-auto-start"])
        for service in services:
            fpm_arguments.extend(["--deb-systemd", service])
    if pre_install := arguments.preinst_file:
        fpm_arguments.extend(["--before-install", pre_install, "--before-upgrade", pre_install])
    if post_install := arguments.postinst_file:
        fpm_arguments.extend(["--after-install", post_install, "--after-upgrade", post_install])
    if pre_remove := arguments.prerm_file:
        fpm_arguments.extend(["--before-remove", pre_remove])
    if post_remove := arguments.postrm_file:
        fpm_arguments.extend(["--after-remove", post_remove])

    command = ["fpm", *fpm_arguments, "setup.py"]

    results = run_command(workspace_dir, command, r'.*"(.+\.deb)"')

    for result in results:
        result = get_absolute_path(result, output_dir)
        print(result)


def _get_arguments() -> Namespace:
    parser = ArgumentParser(formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument("-a", "--arguments", help="extra arguments passed to fpm")
    parser.add_argument("-p", "--python-bin", help="python executable to use")
    parser.add_argument("-o", "--output-dir", help="package output directory")
    parser.add_argument("-s", "--service-file", action="append", help="service unit file path")
    parser.add_argument("--preinst-file", help="preinst file path")
    parser.add_argument("--postinst-file", help="postinst file path")
    parser.add_argument("--prerm-file", help="prerm file path")
    parser.add_argument("--postrm-file", help="postrm file path")
    parser.add_argument("workspace_dir", help="workspace directory where setup.py is located")
    return parser.parse_known_args()[0]


if __name__ == "__main__":
    main()
