#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

import re
import subprocess
from argparse import (
    ArgumentParser,
    ArgumentDefaultsHelpFormatter,
    Namespace,
    BooleanOptionalAction,
)
from configparser import ConfigParser
from os.path import exists, dirname, abspath

from common import check_workspace, get_absolute_path

DEFAULT_PACKAGING = 'wheel'


def main() -> None:
    arguments = _get_arguments()

    workspace_dir = abspath(arguments.workspace_dir)

    check_workspace(workspace_dir)

    config_file = get_absolute_path(arguments.config_file, workspace_dir)

    configuration: dict[str, str] = {}

    if arguments.scripts:
        packaging = arguments.scripts.split()
    else:
        configuration, packaging = _parse_config(arguments, config_file)

    scripts_dir = f'{abspath(dirname(__file__))}'

    for script in packaging:
        script_file = f'{scripts_dir}/{script}'

        if exists(script_file):
            command = [script_file, workspace_dir]

            if arg_string := configuration.get(script):
                command.extend(_split_arguments(arg_string))

            _run_script(arguments, command)


def _run_script(arguments: Namespace, command: list[str]) -> None:
    if arguments.python_bin:
        command.extend(['-p', arguments.python_bin])

    if arguments.output_dir:
        command.extend(['-o', arguments.output_dir])

    result = subprocess.run(command, text=True, stdout=subprocess.PIPE)

    if result.returncode:
        exit(result.returncode)

    if result.stdout:
        print(result.stdout.rstrip('\n'))


def _parse_config(arguments: Namespace, config_file: str) -> tuple[dict[str, str], list[str]]:
    configuration = {}
    packaging = [DEFAULT_PACKAGING]

    if exists(config_file):
        parser = ConfigParser()
        parser.read(config_file)

        if parser.has_section('pack-python'):
            configuration = dict(parser['pack-python'])

            packaging_options = configuration.get('packaging', '').split()

            if arguments.all:
                packaging = packaging_options
            else:
                default = configuration.get('default', DEFAULT_PACKAGING)
                packaging = [default]

    return configuration, packaging


def _get_arguments() -> Namespace:
    parser = ArgumentParser(formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument('-s', '--scripts', help='space separated packaging scripts to run')
    parser.add_argument('-a', '--all', help='run all configured packaging scripts',
                        action=BooleanOptionalAction, default=False)
    parser.add_argument('-c', '--config-file', help='config file path relative to workspace directory',
                        default='setup.cfg')
    parser.add_argument('-p', '--python-bin', help='python executable to use', default='python3')
    parser.add_argument('-o', '--output-dir', help='package output directory')
    parser.add_argument('workspace_dir', help='workspace directory where setup.py is located')
    return parser.parse_args()


def _split_arguments(arg_string: str) -> list[str]:
    # Split on spaces, but allow spaces inside double quotes
    pattern = r'\"(.*?)\"|(\S+)'
    matches = re.findall(pattern, arg_string)
    return [match[0] if match[0] else match[1] for match in matches]


if __name__ == '__main__':
    main()
