name: Python test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-virtualenv python3-all
          pip install wheel stdeb
      - name: Install fpm dependencies
        run: |
          sudo apt-get install -y ruby ruby-dev rubygems build-essential
          sudo gem install -N fpm
      - name: Install dh-virtualenv dependencies
        run: |
          sudo apt-get install -y build-essential debhelper devscripts equivs dh-virtualenv dh-python
      - name: Verify code quality
        run: |
          cd python
          pip install mypy flake8 pytest
          mypy
          flake8
          pytest
