name: Python test

on:
  push:
    branches: main
    tags: v*.*.*

  pull_request:
    branches: [ "main" ]
    types:
      - synchronize
      - opened
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-virtualenv python3-all
          pip install wheel stdeb
      - name: Install fpm dependencies
        run: |
          sudo apt-get install -y ruby ruby-dev rubygems build-essential
          sudo gem install -N fpm
      - name: Install dh-virtualenv dependencies
        run: |
          sudo apt-get install -y debhelper devscripts equivs dh-virtualenv dh-python
      - name: Verify code quality
        run: |
          cd python
          pip install mypy flake8 pytest
          mypy
          flake8
          pytest
      - name: Create Release Bundle
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./build.sh
      - 
        name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            dist/*.tar.gz
